### ISSUE TITLE
Full CV List

### ISSUE THREAD

**Issue by Topolroot** [peteGSX/programmable-dcc-turntable#8]
### Choose a project

Programmable DCC turntable controller

### Feature details

Where can I find the full list of supported CV's? 
Is it possible to change the engine speed, as well as acceleration and braking? 
I want to make a light. Is it possible to add a light switch function (multiple functions) using the usual accessory command?

**Comment by peteGSX** [comment]
Everything I've done with this is documented on [GitHub Pages](https://petegsx-projects.github.io/turntable-controller/index.html) as per the README. The only CVs in use are what's there.

Also, as per my note in there, I'm not likely to change any of this any more, so if you wish to add new features or change things, then feel free to fork the repo and make it suit your requirements. I'll likely change this to a public read only archive at some point.

Cheers, Pete

**Comment by Topolroot** [comment]
Thank you from the bottom of my heart!
